gen:
	./genModel.sh order homestay_order

	./genModel.sh payment third_payment

	./genModel.sh travel homestay
	./genModel.sh travel homestay_activity
	./genModel.sh travel homestay_business
	./genModel.sh travel homestay_comment

	./genModel.sh usercenter user
	./genModel.sh usercenter user_auth